#!/usr/bin/python3
if __name__ == '__main.py__':
    import sys
    if len(sys.argv) == 1:
        print('{}'.format(0))
    else:
        for  _ in sys.argv:
            if _ == sys.argv[0]:
                continue
            _ += int(_)
        print(_)
